import { Inter } from "next/font/google";
import "./globals.css";
import UserReducer from "@/utils/userContext";
import { NextUIProvider } from "@nextui-org/react";
import NavBarComponent from "@/components/Navbar";
import connectDb from "@/utils/db";

const inter = Inter({ subsets: ["latin"] });
connectDb();
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <NavBarComponent />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
